export type {
  ApiEnvelope,
  ClaudeDoc,
  Contract,
  ContractMeta,
  FeatureSpec,
  GitCommit,
  GitHubIssue,
  GitHubPullRequest,
  GitHubSummary,
  IntakeListItem,
  IntakePrompts,
  IntakeStage,
  IntakeStageResponse,
  IntakeStatus,
  Product,
  ProductMeta,
  ProductStatus,
  ProductTheme,
  TodoItem,
  EntitySpec,
  FieldSpec,
  RelationSpec,
  DecisionSpec,
  ModuleSpec,
  ModuleColor,
  ModuleGroup,
  ModuleWithFeatures,
  FieldRequired,
  FeaturePoint,
  FeaturePointPreview,
  FeatureClue,
  RefineTask,
  TaskStage,
  DesignDoc,
  DesignSummary,
  // 批次 1' · 反馈池(精简后只剩 id/date/content)
  Feedback,
  // 批次 3' · 全局需求池
  GlobalFeedback,
  GlobalFeedbackScope,
  GlobalFeedbackData,
  // feature-source-contract 三种约束承载
  FeatureFieldRow,
  StateTransitionRow,
  FieldPermissionRow,
  // 全局角色注册表(data/roles.yml)
  RoleDef,
  RolesRegistry,
  // 产品规格层(Layer 2)文件
  SpecFile,
  SpecFileKind,
  // 产品愿景层(Layer 1)文件
  ProductVision,
  // 决策日志(DECISIONS.md)
  Decision,
  DecisionStatus,
  // 跨模块接缝契约(SEAMS.md)
  Seam,
  // 实体归属表(ENTITIES-OWNERSHIP.md)
  OwnershipRow,
  OwnershipGroupRow,
  OwnershipEntityRow,
  EntitiesOwnershipData,
  // Path C 派生实体
  DerivedEntity,
  DerivedEntitiesData,
  DerivedEntityQuestionsData,
  EntityQuestion,
  EntityReconcileDiff,
  EntityReconcileReport,
  // 架构警告
  ArchitecturalWarning,
  ArchitecturalWarningsData,
  WarningStatus,
  // L0 违规
  L0Violation,
  L0ViolationsData,
  // Feature 重叠检测
  OverlapGroup,
  OverlapReport,
  // v0.1 rev3 五层骨架
  Actor,
  ActorType,
  ActorSource,
  ActorWithRefs,
  Capability,
  CapabilityStatus,
  CapabilityPriority,
  CapabilitySource,
  CapabilityWithRefs,
  UseCase,
  ReferenceIntegrityIssue
} from "@atlas/shared";
