export type {
  ApiEnvelope,
  ClaudeDoc,
  Contract,
  ContractMeta,
  FeatureSpec,
  GitCommit,
  GitHubIssue,
  GitHubPullRequest,
  GitHubSummary,
  IntakeListItem,
  IntakePrompts,
  IntakeStage,
  IntakeStageResponse,
  IntakeStatus,
  Product,
  ProductMeta,
  ProductStatus,
  ProductTheme,
  TodoItem,
  EntitySpec,
  FieldSpec,
  RelationSpec,
  DecisionSpec,
  ModuleSpec,
  ModuleColor,
  ModuleGroup,
  ModuleWithFeatures,
  FieldRequired,
  FeaturePoint,
  FeaturePointPreview,
  FeatureClue,
  RefineTask,
  TaskStage,
  DesignDoc,
  DesignSummary,
  // 批次 1' · 反馈池(精简后只剩 id/date/content)
  Feedback,
  // 批次 3' · 全局需求池
  GlobalFeedback,
  GlobalFeedbackScope,
  GlobalFeedbackData,
  // feature-source-contract 三种约束承载
  FeatureFieldRow,
  StateTransitionRow,
  FieldPermissionRow,
  // 全局角色注册表(data/roles.yml)
  RoleDef,
  RolesRegistry,
  // 流程图 derived 数据 (data/products/<id>/derived/flowcharts/)
  FlowchartData,
  FlowchartQuestion,
  // 产品规格层(Layer 2)文件
  SpecFile,
  SpecFileKind,
  // 产品愿景层(Layer 1)文件
  ProductVision
} from "@atlas/shared";
